# Generated by Django 4.2.3 on 2023-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYLLABUSTRACKERAPP', '0002_day_rename_courses_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.CharField(max_length=250)),
                ('Active', models.BooleanField()),
            ],
        ),
    ]
